/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Hello */

#ifndef _Included_Hello
#define _Included_Hello
#ifdef __cplusplus
extern "C"
{
#endif
  /*
   * Class:     Hello
   * Method:    getCount
   * Signature: ()I
   */
  JNIEXPORT jint JNICALL Java_Hello_getCount(JNIEnv *, jclass);

  /*
   * Class:     Hello
   * Method:    setCount
   * Signature: (I)V
   */
  JNIEXPORT void JNICALL Java_Hello_setCount(JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
